platform :ios, '11.3'

target 'Counter' do
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRealm'
  pod 'RealmSwift'

  target 'CounterTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

  target 'CounterUITests' do
    inherit! :search_paths
  end
end
